# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `faye-websocket` gem.
# Please instead update this file by running `bin/tapioca gem faye-websocket`.


# Copyright (c) 2009-2011 Pratik Naik
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
# Copyright (c) 2009-2011 Pratik Naik
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
# pkg:gem/faye-websocket#lib/faye/websocket.rb:13
module Faye; end

# pkg:gem/faye-websocket#lib/faye/eventsource.rb:4
class Faye::EventSource
  include ::WebSocket::Driver::EventEmitter
  include ::Faye::WebSocket::API::EventTarget

  # pkg:gem/faye-websocket#lib/faye/eventsource.rb:21
  def initialize(env, options = T.unsafe(nil)); end

  # pkg:gem/faye-websocket#lib/faye/eventsource.rb:100
  def close; end

  # pkg:gem/faye-websocket#lib/faye/eventsource.rb:7
  def env; end

  # pkg:gem/faye-websocket#lib/faye/eventsource.rb:57
  def last_event_id; end

  # pkg:gem/faye-websocket#lib/faye/eventsource.rb:94
  def ping(message = T.unsafe(nil)); end

  # pkg:gem/faye-websocket#lib/faye/eventsource.rb:61
  def rack_response; end

  # pkg:gem/faye-websocket#lib/faye/eventsource.rb:7
  def ready_state; end

  # pkg:gem/faye-websocket#lib/faye/eventsource.rb:79
  def send(message, options = T.unsafe(nil)); end

  # pkg:gem/faye-websocket#lib/faye/eventsource.rb:7
  def url; end

  private

  # pkg:gem/faye-websocket#lib/faye/eventsource.rb:67
  def open; end

  class << self
    # pkg:gem/faye-websocket#lib/faye/eventsource.rb:17
    def determine_url(env); end

    # pkg:gem/faye-websocket#lib/faye/eventsource.rb:11
    def eventsource?(env); end
  end
end

# pkg:gem/faye-websocket#lib/faye/eventsource.rb:9
Faye::EventSource::DEFAULT_RETRY = T.let(T.unsafe(nil), Integer)

# pkg:gem/faye-websocket#lib/faye/eventsource.rb:112
class Faye::EventSource::Stream < ::Faye::RackStream
  # pkg:gem/faye-websocket#lib/faye/eventsource.rb:113
  def fail; end
end

# pkg:gem/faye-websocket#lib/faye/rack_stream.rb:2
class Faye::RackStream
  include ::EventMachine::Deferrable

  # pkg:gem/faye-websocket#lib/faye/rack_stream.rb:18
  def initialize(socket); end

  # pkg:gem/faye-websocket#lib/faye/rack_stream.rb:55
  def clean_rack_hijack; end

  # pkg:gem/faye-websocket#lib/faye/rack_stream.rb:61
  def close_connection; end

  # pkg:gem/faye-websocket#lib/faye/rack_stream.rb:66
  def close_connection_after_writing; end

  # pkg:gem/faye-websocket#lib/faye/rack_stream.rb:71
  def each(&callback); end

  # pkg:gem/faye-websocket#lib/faye/rack_stream.rb:75
  def fail; end

  # pkg:gem/faye-websocket#lib/faye/rack_stream.rb:30
  def hijack_rack_socket; end

  # pkg:gem/faye-websocket#lib/faye/rack_stream.rb:78
  def receive(data); end

  # pkg:gem/faye-websocket#lib/faye/rack_stream.rb:81
  def write(data); end
end

# pkg:gem/faye-websocket#lib/faye/rack_stream.rb:6
module Faye::RackStream::Reader
  # pkg:gem/faye-websocket#lib/faye/rack_stream.rb:9
  def receive_data(data); end

  # pkg:gem/faye-websocket#lib/faye/rack_stream.rb:7
  def stream; end

  # pkg:gem/faye-websocket#lib/faye/rack_stream.rb:7
  def stream=(_arg0); end

  # pkg:gem/faye-websocket#lib/faye/rack_stream.rb:13
  def unbind; end
end

# pkg:gem/faye-websocket#lib/faye/websocket.rb:17
class Faye::WebSocket
  include ::WebSocket::Driver::EventEmitter
  include ::Faye::WebSocket::API::EventTarget
  include ::Faye::WebSocket::API

  # pkg:gem/faye-websocket#lib/faye/websocket.rb:69
  def initialize(env, protocols = T.unsafe(nil), options = T.unsafe(nil)); end

  # pkg:gem/faye-websocket#lib/faye/websocket.rb:66
  def env; end

  # pkg:gem/faye-websocket#lib/faye/websocket.rb:91
  def rack_response; end

  # pkg:gem/faye-websocket#lib/faye/websocket.rb:85
  def start_driver; end

  class << self
    # pkg:gem/faye-websocket#lib/faye/websocket.rb:31
    def determine_url(env, schemes = T.unsafe(nil)); end

    # pkg:gem/faye-websocket#lib/faye/websocket.rb:40
    def ensure_reactor_running; end

    # pkg:gem/faye-websocket#lib/faye/websocket.rb:45
    def load_adapter(backend); end

    # pkg:gem/faye-websocket#lib/faye/websocket.rb:52
    def secure_request?(env); end

    # pkg:gem/faye-websocket#lib/faye/websocket.rb:62
    def websocket?(env); end
  end
end

# pkg:gem/faye-websocket#lib/faye/websocket.rb:25
Faye::WebSocket::ADAPTERS = T.let(T.unsafe(nil), Hash)

# pkg:gem/faye-websocket#lib/faye/websocket/api/event_target.rb:1
module Faye::WebSocket::API
  include ::WebSocket::Driver::EventEmitter
  include ::Faye::WebSocket::API::EventTarget
  extend ::Forwardable

  # pkg:gem/faye-websocket#lib/faye/websocket/api.rb:22
  def initialize(options = T.unsafe(nil)); end

  # pkg:gem/faye-websocket#lib/faye/websocket/api.rb:20
  def buffered_amount; end

  # pkg:gem/faye-websocket#lib/faye/websocket/api.rb:90
  def close(code = T.unsafe(nil), reason = T.unsafe(nil)); end

  # pkg:gem/faye-websocket#lib/faye/websocket/api.rb:85
  def ping(message = T.unsafe(nil), &callback); end

  # pkg:gem/faye-websocket#lib/faye/websocket/api.rb:109
  def protocol; end

  # pkg:gem/faye-websocket#lib/faye/websocket/api.rb:20
  def ready_state; end

  # pkg:gem/faye-websocket#lib/faye/websocket/api.rb:66
  def send(message); end

  # pkg:gem/faye-websocket#lib/faye/websocket/api.rb:20
  def url; end

  # pkg:gem/faye-websocket#lib/faye/websocket/api.rb:18
  def version(*args, **_arg1, &block); end

  # pkg:gem/faye-websocket#lib/faye/websocket/api.rb:62
  def write(data); end

  private

  # pkg:gem/faye-websocket#lib/faye/websocket/api.rb:138
  def begin_close(reason, code, options = T.unsafe(nil)); end

  # pkg:gem/faye-websocket#lib/faye/websocket/api.rb:130
  def emit_error(message); end

  # pkg:gem/faye-websocket#lib/faye/websocket/api.rb:154
  def finalize_close; end

  # pkg:gem/faye-websocket#lib/faye/websocket/api.rb:115
  def open; end

  # pkg:gem/faye-websocket#lib/faye/websocket/api.rb:169
  def parse(data); end

  # pkg:gem/faye-websocket#lib/faye/websocket/api.rb:123
  def receive_message(data); end
end

# pkg:gem/faye-websocket#lib/faye/websocket/api.rb:11
Faye::WebSocket::API::CLOSED = T.let(T.unsafe(nil), Integer)

# pkg:gem/faye-websocket#lib/faye/websocket/api.rb:13
Faye::WebSocket::API::CLOSE_TIMEOUT = T.let(T.unsafe(nil), Integer)

# pkg:gem/faye-websocket#lib/faye/websocket/api.rb:10
Faye::WebSocket::API::CLOSING = T.let(T.unsafe(nil), Integer)

# pkg:gem/faye-websocket#lib/faye/websocket/api.rb:8
Faye::WebSocket::API::CONNECTING = T.let(T.unsafe(nil), Integer)

# pkg:gem/faye-websocket#lib/faye/websocket/api/event.rb:36
class Faye::WebSocket::API::CloseEvent < ::Faye::WebSocket::API::Event
  # pkg:gem/faye-websocket#lib/faye/websocket/api/event.rb:37
  def code; end

  # pkg:gem/faye-websocket#lib/faye/websocket/api/event.rb:37
  def reason; end
end

# pkg:gem/faye-websocket#lib/faye/websocket/api/event.rb:40
class Faye::WebSocket::API::ErrorEvent < ::Faye::WebSocket::API::Event
  # pkg:gem/faye-websocket#lib/faye/websocket/api/event.rb:41
  def message; end
end

# pkg:gem/faye-websocket#lib/faye/websocket/api/event.rb:3
class Faye::WebSocket::API::Event
  # pkg:gem/faye-websocket#lib/faye/websocket/api/event.rb:11
  def initialize(event_type, options); end

  # pkg:gem/faye-websocket#lib/faye/websocket/api/event.rb:4
  def bubbles; end

  # pkg:gem/faye-websocket#lib/faye/websocket/api/event.rb:4
  def cancelable; end

  # pkg:gem/faye-websocket#lib/faye/websocket/api/event.rb:5
  def current_target; end

  # pkg:gem/faye-websocket#lib/faye/websocket/api/event.rb:5
  def current_target=(_arg0); end

  # pkg:gem/faye-websocket#lib/faye/websocket/api/event.rb:5
  def event_phase; end

  # pkg:gem/faye-websocket#lib/faye/websocket/api/event.rb:5
  def event_phase=(_arg0); end

  # pkg:gem/faye-websocket#lib/faye/websocket/api/event.rb:16
  def init_event(event_type, can_bubble, cancelable); end

  # pkg:gem/faye-websocket#lib/faye/websocket/api/event.rb:25
  def prevent_default; end

  # pkg:gem/faye-websocket#lib/faye/websocket/api/event.rb:22
  def stop_propagation; end

  # pkg:gem/faye-websocket#lib/faye/websocket/api/event.rb:5
  def target; end

  # pkg:gem/faye-websocket#lib/faye/websocket/api/event.rb:5
  def target=(_arg0); end

  # pkg:gem/faye-websocket#lib/faye/websocket/api/event.rb:4
  def type; end

  class << self
    # pkg:gem/faye-websocket#lib/faye/websocket/api/event.rb:51
    def create(type, options = T.unsafe(nil)); end
  end
end

# pkg:gem/faye-websocket#lib/faye/websocket/api/event.rb:8
Faye::WebSocket::API::Event::AT_TARGET = T.let(T.unsafe(nil), Integer)

# pkg:gem/faye-websocket#lib/faye/websocket/api/event.rb:9
Faye::WebSocket::API::Event::BUBBLING_PHASE = T.let(T.unsafe(nil), Integer)

# pkg:gem/faye-websocket#lib/faye/websocket/api/event.rb:7
Faye::WebSocket::API::Event::CAPTURING_PHASE = T.let(T.unsafe(nil), Integer)

# pkg:gem/faye-websocket#lib/faye/websocket/api/event_target.rb:2
module Faye::WebSocket::API::EventTarget
  include ::WebSocket::Driver::EventEmitter

  # pkg:gem/faye-websocket#lib/faye/websocket/api/event_target.rb:16
  def add_event_listener(event_type, listener, use_capture = T.unsafe(nil)); end

  # pkg:gem/faye-websocket#lib/faye/websocket/api/event_target.rb:20
  def add_listener(event_type, callable = T.unsafe(nil), &block); end

  # pkg:gem/faye-websocket#lib/faye/websocket/api/event_target.rb:32
  def dispatch_event(event); end

  # pkg:gem/faye-websocket#lib/faye/websocket/api/event_target.rb:8
  def onclose=(handler); end

  # pkg:gem/faye-websocket#lib/faye/websocket/api/event_target.rb:8
  def onerror=(handler); end

  # pkg:gem/faye-websocket#lib/faye/websocket/api/event_target.rb:8
  def onmessage=(handler); end

  # pkg:gem/faye-websocket#lib/faye/websocket/api/event_target.rb:8
  def onopen=(handler); end

  # pkg:gem/faye-websocket#lib/faye/websocket/api/event_target.rb:28
  def remove_event_listener(event_type, listener, use_capture = T.unsafe(nil)); end

  private

  # pkg:gem/faye-websocket#lib/faye/websocket/api/event_target.rb:55
  def event_buffers; end

  # pkg:gem/faye-websocket#lib/faye/websocket/api/event_target.rb:49
  def flush(event_type, listener); end
end

# pkg:gem/faye-websocket#lib/faye/websocket/api/event.rb:32
class Faye::WebSocket::API::MessageEvent < ::Faye::WebSocket::API::Event
  # pkg:gem/faye-websocket#lib/faye/websocket/api/event.rb:33
  def data; end
end

# pkg:gem/faye-websocket#lib/faye/websocket/api.rb:9
Faye::WebSocket::API::OPEN = T.let(T.unsafe(nil), Integer)

# pkg:gem/faye-websocket#lib/faye/websocket/api/event.rb:29
class Faye::WebSocket::API::OpenEvent < ::Faye::WebSocket::API::Event; end

# pkg:gem/faye-websocket#lib/faye/websocket/api/event.rb:44
Faye::WebSocket::API::TYPES = T.let(T.unsafe(nil), Hash)

# pkg:gem/faye-websocket#lib/faye/websocket/adapter.rb:4
module Faye::WebSocket::Adapter
  # pkg:gem/faye-websocket#lib/faye/websocket/adapter.rb:10
  def eventsource?; end

  # pkg:gem/faye-websocket#lib/faye/websocket/adapter.rb:15
  def socket_connection?; end

  # pkg:gem/faye-websocket#lib/faye/websocket/adapter.rb:5
  def websocket?; end
end

# pkg:gem/faye-websocket#lib/faye/websocket/client.rb:6
class Faye::WebSocket::Client
  include ::WebSocket::Driver::EventEmitter
  include ::Faye::WebSocket::API::EventTarget
  include ::Faye::WebSocket::API
  extend ::Forwardable

  # pkg:gem/faye-websocket#lib/faye/websocket/client.rb:15
  def initialize(url, protocols = T.unsafe(nil), options = T.unsafe(nil)); end

  # pkg:gem/faye-websocket#lib/faye/websocket/client.rb:13
  def headers(*args, **_arg1, &block); end

  # pkg:gem/faye-websocket#lib/faye/websocket/client.rb:13
  def status(*args, **_arg1, &block); end

  private

  # pkg:gem/faye-websocket#lib/faye/websocket/client.rb:42
  def configure_proxy(proxy); end

  # pkg:gem/faye-websocket#lib/faye/websocket/client.rb:67
  def on_connect(stream); end

  # pkg:gem/faye-websocket#lib/faye/websocket/client.rb:75
  def on_network_error(error); end

  # pkg:gem/faye-websocket#lib/faye/websocket/client.rb:86
  def ssl_handshake_completed; end

  # pkg:gem/faye-websocket#lib/faye/websocket/client.rb:80
  def ssl_verify_peer(cert); end

  # pkg:gem/faye-websocket#lib/faye/websocket/client.rb:59
  def start_tls(uri, options); end
end

# pkg:gem/faye-websocket#lib/faye/websocket/client.rb:92
module Faye::WebSocket::Client::Connection
  # pkg:gem/faye-websocket#lib/faye/websocket/client.rb:95
  def connection_completed; end

  # pkg:gem/faye-websocket#lib/faye/websocket/client.rb:93
  def parent; end

  # pkg:gem/faye-websocket#lib/faye/websocket/client.rb:93
  def parent=(_arg0); end

  # pkg:gem/faye-websocket#lib/faye/websocket/client.rb:107
  def receive_data(data); end

  # pkg:gem/faye-websocket#lib/faye/websocket/client.rb:103
  def ssl_handshake_completed; end

  # pkg:gem/faye-websocket#lib/faye/websocket/client.rb:99
  def ssl_verify_peer(cert); end

  # pkg:gem/faye-websocket#lib/faye/websocket/client.rb:111
  def unbind(error = T.unsafe(nil)); end

  # pkg:gem/faye-websocket#lib/faye/websocket/client.rb:116
  def write(data); end
end

# pkg:gem/faye-websocket#lib/faye/websocket/client.rb:10
Faye::WebSocket::Client::DEFAULT_PORTS = T.let(T.unsafe(nil), Hash)

# pkg:gem/faye-websocket#lib/faye/websocket/client.rb:11
Faye::WebSocket::Client::SECURE_PROTOCOLS = T.let(T.unsafe(nil), Array)

# pkg:gem/faye-websocket#lib/faye/websocket/ssl_verifier.rb:26
class Faye::WebSocket::SSLError < ::OpenSSL::SSL::SSLError; end

# pkg:gem/faye-websocket#lib/faye/websocket/ssl_verifier.rb:28
class Faye::WebSocket::SslVerifier
  # pkg:gem/faye-websocket#lib/faye/websocket/ssl_verifier.rb:29
  def initialize(hostname, ssl_opts); end

  # pkg:gem/faye-websocket#lib/faye/websocket/ssl_verifier.rb:56
  def ssl_handshake_completed; end

  # pkg:gem/faye-websocket#lib/faye/websocket/ssl_verifier.rb:41
  def ssl_verify_peer(cert_text); end

  private

  # pkg:gem/faye-websocket#lib/faye/websocket/ssl_verifier.rb:86
  def identity_verified?; end

  # pkg:gem/faye-websocket#lib/faye/websocket/ssl_verifier.rb:74
  def parse_cert(cert_text); end

  # pkg:gem/faye-websocket#lib/faye/websocket/ssl_verifier.rb:70
  def should_verify?; end

  # pkg:gem/faye-websocket#lib/faye/websocket/ssl_verifier.rb:80
  def store_cert(certificate); end
end

# pkg:gem/faye-websocket#lib/faye/websocket.rb:96
class Faye::WebSocket::Stream < ::Faye::RackStream
  # pkg:gem/faye-websocket#lib/faye/websocket.rb:97
  def fail; end

  # pkg:gem/faye-websocket#lib/faye/websocket.rb:101
  def receive(data); end
end
