# frozen_string_literal: true

source "https://rubygems.org"

ruby ">= 3.3"

gem "sinatra", "~> 4.0"
gem "puma", "~> 6.0"
gem "faye-websocket", "~> 0.11"
gem "rackup", "~> 2.0"
gem "sorbet-runtime"
gem "sqlite3", "~> 2.0"

group :development do
  gem "sorbet"
  gem "tapioca", require: false
end

group :test do
  gem "rspec", "~> 3.13"
  gem "rack-test"
  gem "simplecov", require: false
end

group :development, :test do
  gem "rubocop", require: false
end
