# DO NOT EDIT MANUALLY
# This is an autogenerated file for unresolved constants.
# Please instead update this file by running `bin/tapioca todo`.

# typed: false

module ::Anonymous_Delegator_1; end
module ::Anonymous_Delegator_2; end
module ::Anonymous_Delegator_7; end
module ::SimpleCov; end
module Rake::DSL; end
module Rake::FileUtilsExt; end
